// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Bindings for `src/rust_net.h`.
///
/// Regenerate bindings with `dart run ffigen --config ffigen.yaml`.
///
class RustNetBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustNetBindings(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  RustNetBindings.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  int rust_net_client_create(
    ffi.Pointer<ffi.Char> config_json,
  ) {
    return _rust_net_client_create(
      config_json,
    );
  }

  late final _rust_net_client_createPtr =
      _lookup<ffi.NativeFunction<ffi.Uint64 Function(ffi.Pointer<ffi.Char>)>>(
          'rust_net_client_create');
  late final _rust_net_client_create = _rust_net_client_createPtr
      .asFunction<int Function(ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<ffi.Char> rust_net_client_execute(
    int client_id,
    ffi.Pointer<ffi.Char> request_json,
  ) {
    return _rust_net_client_execute(
      client_id,
      request_json,
    );
  }

  late final _rust_net_client_executePtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
              ffi.Uint64, ffi.Pointer<ffi.Char>)>>('rust_net_client_execute');
  late final _rust_net_client_execute = _rust_net_client_executePtr
      .asFunction<ffi.Pointer<ffi.Char> Function(int, ffi.Pointer<ffi.Char>)>();

  void rust_net_client_close(
    int client_id,
  ) {
    return _rust_net_client_close(
      client_id,
    );
  }

  late final _rust_net_client_closePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Uint64)>>(
          'rust_net_client_close');
  late final _rust_net_client_close =
      _rust_net_client_closePtr.asFunction<void Function(int)>();

  void rust_net_string_free(
    ffi.Pointer<ffi.Char> value,
  ) {
    return _rust_net_string_free(
      value,
    );
  }

  late final _rust_net_string_freePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Char>)>>(
          'rust_net_string_free');
  late final _rust_net_string_free = _rust_net_string_freePtr
      .asFunction<void Function(ffi.Pointer<ffi.Char>)>();
}
